{
 "title": "Backend Services - General View",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Quotas",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\n    (sum by(organization_name,organization_id,space_name) (count(cf_service_instance_info) by(service_instance_name, space_id) * on(space_id) group_left(space_name, organization_id) \ncount(cf_space_info{space_name=~\".*-shared|.*-dedicated|.*-extended\"}) by(space_id, space_name, organization_id) * on(organization_id) group_left(organization_name) \ncount(cf_organization_info) by(organization_id, organization_name)))  / ignoring(organization_name) group_left sum by(organization_id,space_name) ( cf_space_total_services_quota), \n    \"short_organization_name\", \n    \"$1\", \n    \"organization_name\", \n    \"cmdb-(.*)-services\"\n    )",
     "legendFormat": "{{short_organization_name}}-{{space_name}}"
    }
   ]
  },
  {
   "title": "Dedicated Services by Consumer",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "label_replace(\n    sum(\ncount(cf_service_instance_info) by(service_instance_name, space_id) * on(space_id) group_left(space_name, organization_id) \ncount(cf_space_info{space_name=~\".*-dedicated|.*extended\"}) by(space_id, space_name, organization_id) * on(organization_id) group_left(organization_name) \ncount(cf_organization_info) by(organization_id, organization_name)\n) \nby(organization_name, space_name), \n    \"short_organization_name\", \n    \"$1\", \n    \"organization_name\", \n    \"cmdb-(.*)-services\"\n    )",
     "legendFormat": "{{short_organization_name}}-{{space_name}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Dedicated Services by type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (bosh_deployment)(bosh_deployment_instances{bosh_deployment=~\"m_.*\"}))",
     "legendFormat": "mongoDB"
    },
    {
     "expr": "count(sum by (bosh_deployment)(bosh_deployment_instances{bosh_deployment=~\"y_.*\"}))",
     "legendFormat": "mariaDB"
    },
    {
     "expr": "count(sum by (bosh_deployment)(bosh_deployment_instances{bosh_deployment=~\"r_.*\"}))",
     "legendFormat": "rabbitMQ"
    },
    {
     "expr": "count(sum by (bosh_deployment)(bosh_deployment_instances{bosh_deployment=~\"e_.*\"}))",
     "legendFormat": "Redis"
    },
    {
     "expr": "count(sum by (bosh_deployment)(bosh_deployment_instances{bosh_deployment=~\"t_.*\"}))",
     "legendFormat": "mariaDB HA"
    }
   ]
  },
  {
   "title": "Shared Services by consumer",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 13 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "label_replace(\n    sum(\ncount(cf_service_instance_info) by(service_instance_name, space_id) * on(space_id) group_left(space_name, organization_id) \ncount(cf_space_info{space_name=~\".*-shared\"}) by(space_id, space_name, organization_id) * on(organization_id) group_left(organization_name) \ncount(cf_organization_info) by(organization_id, organization_name)\n) \nby(organization_name, space_name), \n    \"short_organization_name\", \n    \"$1\", \n    \"organization_name\", \n    \"[a-z-]*cmdb-(.*)-services[a-z-0-9]*\"\n    )",
     "legendFormat": "{{short_organization_name}}-{{space_name}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Dedicated Services",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum by (bosh_deployment)(bosh_deployment_instances{bosh_deployment=~\"[a-z]_.*\"}))"
    }
   ]
  },
  {
   "title": "# R1 VMs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (bosh_job_healthy{bosh_job_az=~\"z.*\"})"
    }
   ]
  },
  {
   "title": "# R2 VMs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (bosh_job_healthy{bosh_job_az=~\"r2.*\"})"
    }
   ]
  },
  {
   "title": "# R3 VMs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (bosh_job_healthy{bosh_job_az=~\"r3.*\"})"
    }
   ]
  },
  {
   "title": "Dedicated Public IP (r1)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "sum (bosh_job_healthy{bosh_job_name=~\".*proxy.*|.*haproxy.*|.*redis.*|.*redis-master.*|.*redis-slave.*|.*mongod.*\",bosh_name=\"bosh-coab\",bosh_job_az=~\"z.*\"})"
    }
   ]
  },
  {
   "title": "Dedicated Public IP (r2)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 15, "y": 15 },
   "targets": [
    {
     "expr": "sum (bosh_job_healthy{bosh_job_name=~\".*proxy.*|.*haproxy.*|.*redis.*|.*redis-master.*|.*redis-slave.*|.*mongod.*\",bosh_name=\"bosh-coab\",bosh_job_az=~\"r2-.*\"})"
    }
   ]
  }
 ]
}