{
 "title": "Multi-region VPN Status",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "VPN Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 5, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "min(probe_success{instance=\"192.168.2.2\"})",
     "legendFormat": "R1"
    },
    {
     "expr": "min(probe_success{instance=\"192.168.2.3\"})",
     "legendFormat": "R2"
    },
    {
     "expr": "min(probe_success{instance=\"192.168.2.4\"})",
     "legendFormat": "R3"
    }
   ]
  },
  {
   "title": "R1 instant latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"192.168.2.2\"})",
     "legendFormat": "R1"
    }
   ]
  },
  {
   "title": "R2 instant latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 7, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"192.168.2.3\"})",
     "legendFormat": "R2"
    }
   ]
  },
  {
   "title": "R3 instant latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 14, "y": 5 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"192.168.2.4\"})",
     "legendFormat": "R3"
    }
   ]
  },
  {
   "title": "R1 Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"192.168.2.2\"})",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "R2 Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"192.168.2.3\"})",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "R3 Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"192.168.2.4\"})",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "R1 wg0 Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"192.168.99.45(:[0-9]+)?\", device=\"wg0\"}[10m])",
     "legendFormat": "Inbound"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"192.168.99.45(:[0-9]+)?\", device=\"wg0\"}[10m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "R2 wg0 Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"192.168.117.41(:[0-9]+)?\", device=\"wg0\"}[10m])",
     "legendFormat": "Inbound"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"192.168.117.41(:[0-9]+)?\", device=\"wg0\"}[10m])",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "R3 wg0 Network Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"192.168.118.41(:[0-9]+)?\", device=\"wg0\"}[10m])",
     "legendFormat": "Inbound"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"192.168.118.41(:[0-9]+)?\", device=\"wg0\"}[10m])",
     "legendFormat": "Outbound"
    }
   ]
  }
 ]
}