{
 "title": "VMware stats",
 "description": "Uses prometheus queries via pryorda/vmware_exporter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "dc",
    "label": "datacenter",
    "query": "label_values(vmware_host_connection_state, dc_name)"
   },
   {
    "name": "host",
    "label": "host",
    "query": "label_values(vmware_host_connection_state, host_name)"
   },
   {
    "name": "vm",
    "label": "vm",
    "query": "label_values(vmware_vm_power_state, vm_name)"
   },
   {
    "name": "ds",
    "label": "datastore",
    "query": "label_values(vmware_datastore_capacity_size, ds_name)"
   }
  ]
 },
 "panels": [
  { "title": "High level stats - Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ESXi Memory usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(vmware_host_memory_usage / vmware_host_memory_max)",
     "legendFormat": "{{ host_name }}"
    }
   ]
  },
  {
   "title": "ESXi Memory Free",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "vmware_host_memory_max - vmware_host_memory_usage",
     "legendFormat": "{{ host_name }}"
    }
   ]
  },
  { "title": "High level stats - CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "ESXi CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage / vmware_host_cpu_max)",
     "legendFormat": "{{ host_name }}"
    }
   ]
  },
  { "title": "High level stats - Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Total VMs",
   "type": "singlestat",
   "description": "Total count of virtual machines, regardless of power state.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "count(vmware_vm_power_state)" }
   ]
  },
  {
   "title": "Powered on VMs",
   "type": "singlestat",
   "description": "Count of virtual machines that are currently powered on.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vmware_vm_power_state > 0)"
    }
   ]
  },
  {
   "title": "Powered off VMs",
   "type": "singlestat",
   "description": "Count of virtual machines that are powered off currently.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(vmware_vm_power_state == 0)"
    }
   ]
  },
  {
   "title": "Average vCPUs per VM",
   "type": "singlestat",
   "description": "Average number of virtual CPUs assigned to each VM.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(sum_over_time(vmware_vm_num_cpu[1m])) / sum(count_over_time(vmware_vm_num_cpu[1m]))"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "singlestat",
   "description": "Amount of RAM assigned to each VM, on average.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "format": "decmbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(vmware_host_memory_max - vmware_host_memory_usage)"
    }
   ]
  },
  {
   "title": "Average host core count",
   "type": "singlestat",
   "description": "Average number of CPU cores per host.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "avg(vmware_host_num_cpu)" }
   ]
  },
  {
   "title": "Average host memory",
   "type": "singlestat",
   "description": "Average memory per host.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    { "expr": "avg(vmware_host_memory_max)" }
   ]
  },
  { "title": "Host stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Host CPU usage",
   "type": "graph",
   "description": "Percentage of host CPU consumed over time.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(vmware_host_cpu_usage{host_name=~\"$host\"} / vmware_host_cpu_max) * 100",
     "legendFormat": "{{ dc_name }}/{{ cluster_name }}/{{ host_name }}"
    }
   ]
  },
  {
   "title": "Host memory Free",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(vmware_host_memory_max - vmware_host_memory_usage)"
    }
   ]
  },
  {
   "title": "Datastore storage used %",
   "type": "bargauge",
   "description": "Percentage of datastore usage.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "((vmware_datastore_capacity_size{ds_name=~\"VDR_.*\"} - vmware_datastore_freespace_size) / vmware_datastore_capacity_size) * 100",
     "legendFormat": "{{ dc_name }}/{{ ds_name }}"
    }
   ]
  },
  {
   "title": "Provisioned datastore space",
   "type": "bargauge",
   "description": "Percentage of space provisioned, but not used, within each datastore.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 31 },
   "targets": [
    {
     "expr": "(vmware_datastore_provisoned_size{ds_name=~\"VDR_.*\"} / vmware_datastore_capacity_size) * 100",
     "legendFormat": "{{ dc_name }}/{{ ds_name }}"
    }
   ]
  },
  {
   "title": "Host memory usage %",
   "type": "graph",
   "description": "Percentage of memory consumed on each host currently.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(vmware_host_memory_usage{host_name=~\"$host\"} / vmware_host_memory_max) * 100",
     "legendFormat": "{{ dc_name }}/{{ cluster_name}}/{{ host_name }}"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count(vmware_vm_power_state)" }
   ]
  },
  {
   "title": "VM stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM CPU usage",
     "type": "graph",
     "description": "CPU usage per virtual machine.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "vmware_vm_cpu_demand_average{vm_name=~\"$vm\"} * 1000000",
       "legendFormat": "{{ host_name }}/{{ vm_name }}"
      }
     ]
    },
    {
     "title": "VM memory usage",
     "type": "graph",
     "description": "Memory usage of each virtual machine.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "vmware_vm_mem_consumed_average{vm_name=~\"$vm\"}",
       "legendFormat": "consumed: {{ vm_name }}"
      },
      {
       "expr": "vmware_vm_mem_active_average{vm_name=~\"$vm\"}",
       "legendFormat": "active: {{ vm_name }}"
      }
     ]
    },
    {
     "title": "VM swap usage",
     "type": "graph",
     "description": "Amount of swap each virtual machine is using.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "expr": "vmware_vm_mem_swapped_average{vm_name=~\"$vm\"}",
       "legendFormat": "{{ dc_name }}/{{ cluster_name }}/{{ host_name }}/{{ vm_name }}"
      }
     ]
    },
    {
     "title": "Maximum VM disk latency",
     "type": "graph",
     "description": "Maximum latency experienced by at least one virtual disk of each virtual machine.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "vmware_vm_disk_maxTotalLatency_latest{vm_name=~\"$vm\"}",
       "legendFormat": "{{ vm_name }}"
      }
     ]
    }
   ]
  }
 ]
}