#!/bin/bash

echo "this script takes as input missingx_osb_cmdb.lst file generated by 1_list_coab_instances_without_osbcmdb_params_in_coab_vars.bash"
echo "this script is using osb-cmdb cli function called cf_service_instance_from_guid so you must be connected to master-depls/cf to use it"
echo "this script generates a file containing coab deployments (backing) service instance guid missing from osb-cmdb inventory"

for l in $(cat missingx_osb_cmdb.lst) ; do cf_service_instance_from_guid ${l} ; done > missing.log
cat missing.log | grep "no service instance with guid" | cut -d' ' -f6 > missing_from_inventory.lst
