{
 "title": "OpenEBS Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(openebs_parse_error_total)", "legendFormat": "parse error total" },
    {
     "expr": "sum(openebs_connection_error_total)",
     "legendFormat": "connection error total"
    },
    {
     "expr": "sum(openebs_zfs_list_command_error)",
     "legendFormat": "zfs list command error"
    }
   ]
  },
  {
   "title": "replica count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openebs_degraded_replica_count)",
     "legendFormat": "degraded replica count"
    }
   ]
  },
  {
   "title": "used pool capacity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "avg(openebs_used_pool_capacity_percent)",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Storage evolution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openebs_size_of_volume)",
     "legendFormat": "Sum of size of the volume requested  (Go)"
    },
    {
     "expr": "sum(openebs_actual_used)",
     "legendFormat": "Sum of actual volume size used(Go)"
    }
   ]
  }
 ]
}